### ISSUE TITLE
한 주 한 글 2기를 마무리 하며

### ISSUE THREAD

**Issue by usageness** [TeamCrazyPerformance/one-week-one-post#1]
한 주 한 글 2기에 열정적으로 참여해주신 모든 분들,
10주 동안 정말 고생 많으셨습니다.

이번 한 주 한 글을 마치며 느꼈던 점들을 자유롭게 작성해주세요.
어떤 내용을 적어야 할지 감이 오지 않는다면, 아래 내용들을 참고해보셔도 좋아요.

- **달라진 나의 생활 루틴**
- **매 주 글을 쓰며 얻은 효과**
- **글쓰기를 대하는 태도의 변화**
- **기록에서 오는 즐거움**

## 조건
1. 글 내용은 너무 짧지 않게, 공백 제외 500자 이상
2. 제출 전 [맞춤법 검사기](https://www.saramin.co.kr/zf_user/tools/character-counter) 돌려보기
3. 마크다운(Markdown) 문법을 한껏 활용하셔도 좋습니다.

## 제출 방법
해당 이슈 아래에 코멘트로 제출

---

제출된 글은 다음 기수를 모집할때 함께 공개될 예정이며,
제출 마감은 **6월 30일 금요일**까지입니다.

## 제출 완료
2기 회고들은 [노션 페이지](https://usageness.notion.site/2-0e3e68fbca78431a802e2a1a6c83776b?pvs=4)에서 편하게 확인하실 수 있습니다.

**Comment by gomdoricake** [comment]
한 주 한 글 2기를 마무리 하며... 

안녕하세요, 한 주 한 글 2기의 21학번 전효정입니다.
사실 2023년 1학기는 제게 정말 바쁜 학기였는데요! 동아리 내 스터디 5개(한 주 한 글 스터디를 포함하여 5개 입니다!), 알고리즘 공부, 앱 개발 공모전, 프로젝트 기획, 학교 공부 및 과제, 아르바이트(주 3회), 운동(주 3회), 스쿠버 다이빙 훈련(자주는 아니지만 힘든 일정이기에ㅎㅎ), 새로운 친구들과 놀기(프랑스 친구를 새로 사귀게 되었습니다!) 등등... 한시라도 가만히 있지를 못하는 제 성격 답게 여러 가지 일들을 진행해 왔습니다.

그러다 보면, 제가 이 당시에 무얼 했는지 잘 기억이 나지 않을 때가 많아요. 내가 어떤 공부를 했더라? 내가 이 당시에 무엇을 새롭게 배웠더라? 등등, 정신 없이 의미 없게 시간이 지나가 버리는 것 같기도 합니다. 이것이 저의 단점이랄까요. 무언가를 마~악 저질러 놓고 막상 보면 하나라도 제대로 한 것이 맞나...? 라는 생각이 들게 되는 거죠ㅎㅎ

그런데 한 주 한 글 스터디를 통해, 저의 활동들이 하나씩 기록되는 것이 정말 좋았습니다. 기록하지 않았더라면 그저 지나쳐 갔을 저의 경험 및 활동들이 하나씩 쌓여 가는 것이 눈에 보이게 되었습니다.

한 주 한 글 매주 꾸준히 글을 쓰다보면, 무언가가 차곡차곡 쌓인다는 느낌이 들구요, 또 정말 바쁜 와중에도 글을 써 내는 데에 성공했다는 사실이 내심 뿌듯하기도 합니다. 나중에 나라는 사람을 다른 사람들한테 소개할 때에도 이 글들은 분명 도움이 될 것이구요.

이처럼 본인의 활동을 어딘가에 남겨 두는 것은 분명히 의미가 있습니다. 이것이 1년이 되고, 2년이 되고, 10년이 되었을 때 완성이 될 포트폴리오를 생각해 보세요. 

사실 마감일 전날에 급하게 글을 쓰는 경우도 많았지만, 그렇게라도 글을 써두니 남는 것이 많군요. 
이런 좋은 스터디를 열어 주신 스터디장님, 감사합니다!

2023.6.30.(금)

**Comment by pianoop** [comment]
한 주 한 글을 시작하기 전의 저는 공부한 것을 따로 기록하거나 하지 않았습니다. 시험 기간이나 되어야 요약 노트 같은 것을 만드는 게 다였는데 이 스터디를 참여한 후 매주 공부한 것을 올리려다 보니 별로 급하지 않은 기간에도 글을 올리기 위해 공부한 것을 복습하며 정리하는 시간을 가질 수 있었습니다.   

스터디를 시작하고 중후반쯤엔 다시 복습하고 그러는 게 너무 귀찮아서 처음 공부할 때 바로바로 마크다운으로 필기(?)하기 시작했고 해당 내용을 그대로 글로 올리기도 했었습니다. XD  
그렇게 Md 파일로 과목별로 필기를 해두니 나중에 볼 때도 더 편하더라고요, 귀찮음에서 시작됐지만 괜찮은 습관이 생긴 것 같습니다. 한 주 한 글 덕분이네요. ㅎㅎ   

가끔 스터디원들이 쓴 글들을 보며 힘을 얻은 적도 있습니다. 개인적으로 조금 힘들었던 학기였는데 이러한 것들 덕에 그나마 버틸 수 있었던 것 같네요. 다들 정말 감사드리고 수고 많으셨습니다! 😆

**Comment by shchooii** [comment]
안녕하세요, 한 주 한 글 2기 20학번 최승훈입니다.

이번 주에 저는 주로 코딩 문제 풀이에 대한 글을 작성해보았습니다. 자신의 생각을 정리하고, 그것을 다른 사람이 이해하기 쉽게 전달하는 것은 의외로 어려운 과제였습니다.

제가 사용하는 프로그래밍 언어인 C++로 코딩 문제를 해결하고 나서, main 함수의 작동 원리를 설명한 뒤 각각의 함수에 대해서도 설명해보려 했습니다. 여기서, '더 나은 설명법이 있지 않을까?' 혹은 '도식을 그려서 설명해야 하지 않을까?' 하는 고민들이 생겼습니다.

그러나 이런 고민들이 불구하고, 문제를 풀고나서 그것을 글로 정리하는 과정을 거치면서 문제에 대한 이해도가 깊어졌음을 느꼈습니다. 그저 문제를 풀고 넘어가는 것이 아니라, 그 해결 과정을 누군가에게 설명할 수 있을 정도로 자세히 이해하는 것은 굉장히 가치 있는 경험이었습니다.

읽는 사람에게 더 친숙하게 다가갈 수 있는 글은 결국 그만큼 많은 시간과 노력을 들여 다듬어진 결과물입니다. 한 주 한 글 2기 동안의 경험은 저에게 그런 과정의 중요성을 다시 한번 깨닫게 해주었습니다.

저는 앞으로도 이런 퇴고의 과정을 통해 더 나은 글을 쓸 수 있도록 노력하겠습니다. 그리고 그 과정에서 얻은 지식과 경험을 여러분과 나눌 수 있으면 좋을 것 같습니다. 😃 😃

**Comment by AzureSoda** [comment]
이전부터 선배의 추천으로 블로그를 적고는 있었다. 하지만 나는 원체 수동적인 인간이라서 가끔 생각나면 적는 수준이었는데 이번에 용래선배가 같이 해보자고 추천해주셔서 블로그를 티스토리로 옮기고 다시 적어나가기 시작했다. 평소에도 브런치를 통해서 짧은 글이나 에세이나 리뷰글들을 읽곤해서 나도 언젠간 이런 글들을 잘 적어나고 싶다는 생각을 가지고 있었고 이번 한주 한글 1기, 2기를 통해서 이런 생각을 어느 정도 실현시킨 것 같다. 

그동안 한주 한글 1기, 2기 활동을 하면서 적은 글들을 보면 다양한 분야에 대해서 적었다. 이번 활동하면서 적은 글들은 거의 낙서와 기록 사이에 있는 것 같다. 우선 나의 메인 관심사인 게임 개발에 대한 글들과 그냥 잡다한 생각과 낙서에 가까운 글들과 그동안에 했었던 대외활동들과 학교 공부들과 여러가지 공부한 것들, 그리고 해보고 싶었던 영화, 게임, 음악, 책 등의 리뷰에 대해서 적었었다. 

이번 활동을 하면서 다른 사람들은 주로 개발쪽에 관한 글들을 많이 적어서 내가 이런 글을 적어도 될까 라는 걱정도 했었지만 아무거나 일단 적어보라는 선배의 격려덕에 다양한 분야에 대해서 적어보았던 것 같다.  활동하면서 좋았던 점중 하나는 용래선배가 꼭 읽고나서 표시를 해주신다는 것이었다. 내가 쓴글을 한명은 꼭 읽어준다는 것이 많은 격려가 되었고 감사하게 느껴졌다. 가끔 다른 선배들도 “이번주는 ~~에 대해서 적었더라 ㅎㅎ”, ”블로그에 글쓰는거 보면 평론가같아 ㅎㅎ”  라는 식으로 피드백을 주셨던 것도 한주 한글을 적어나가는데 좋은 원동력이 되었다. 

요즘에는 게임 기획에 관심을 가지면서 게임 리뷰글과 게임 디자인, 레벨 디자인에 대한 글을 적고 있다. 나는 허지웅 작가의 글들을 좋아한다. 그가 쓴 최근의 글들을 보면 짧은 글안에 매우 깔끔하고 하고 싶은 주제까지 잘 전달하고 있다. 나도 그런 글들을 적고 싶은데 생각대로 되지 않아서 글 쓰는데  주저하기도 했었고, 그동안에도 게임 리뷰나 영화리뷰에 대해서 적고 싶었지만 내가 글을 적으면 인터넷 공간의 낭비가 아닐까? 다른 사람들의 생각과 비슷하면 어쩌나? 하고 망설였는데 생각보다 나와 같은 관점에서 바라본 글들이 없었다. 그래서 내가 글을 적어도 되겠구나 하는 생각이 들어서 최근에 한 콘텐츠들부터 리뷰해나가고 있다.

주변 사람들로부터 평소에 증거를 남기라는 이야기를 자주 들었었다. 내가 활동했었던 내용들, 대외 활동이나 프로젝트들에 대해서 기록하는 것이 좋다고 이야기를 들었었는데 이번 한주 한글을 하면서 그동안의 내역들을 정리해나가면서 적을 수 있어서 좋았다. 

또한 글을 적으면서 좋은 점은 생각을 정리해나갈 수 있다는 것이다. 올해 초부터 요즈음까지 많이 흔들리고 있는 나에게 글을 적으면서 생각을 정리하고 “내가 해야 할 것이 무엇인지”, “나는 무엇을 하고 싶은지”, “앞으로 나는 어떻게 해아하는지” 등 자기반성과 목표를 재설정하는데 큰 도움이 되었다.

그리고 요즘 게임 기획을 공부하면서 자주 듣게되는 일인데 표현하는 능력을 기르는 것이 중요하다고 한다. 평소에 생각해두었던 나의 생각들을 글로 적어 옮김으로써 생각을 다시금 정리하고 표현할 수 있었다. 

이번 활동에서의 즐거웠던 점은 쌓여가는 블로그 글들의 수와 조회수 였던 것 같다. 여러 블로그의 글들을 보면 처음에는 글들의 형식도 아직 갖춰지지 않은 형태이지만 점차 갈수록 글들의 형식도 정해지고 퀄리티도 좋아지는 것을 많이 볼 수 있었는데 나도 조만간 이런 블로그가 되었으면 좋겠다는 생각이 든다.

다양한 경험과 체험을 하고 그것을 바탕으로 성장해나가는 것이 중요하다고 평소에 생각하고는 하는데 이번 한주한글 활동이 나에게 좋은 경험이 되었다고 생각한다.

많이 귀찮은 일이었을 텐데도 매주 글을 읽고 피드백 해주어서 고맙다는 말을 이 기회를 통해서 용래선배한테 전한다 ㅎㅎㅎ

현재 내 블로그의 조회수는 899이다. 아마도 우리 동아리 분들이 조회수의 대부분을 차지하고 있을텐데 부족한 글이지만 읽어주어서 감사하고 앞으로도 더 재미있고 흥미있는 글들에 대해서 적어나갈 것이니까 많이들 봐주시고 공감버튼이랑 댓글도 달아주시면 감사하겠다 ㅎㅎ

**Comment by wlsh44** [comment]
한 주 한 글 스터디를 하기 전에도 블로그 글을 쓰긴 썼지만 평소에 글을 잘 안 써서 그런지 거부감을 많이 느꼈는데, 한 주 한 글 스터디에 참여하고 매주 글을 억지로라도 쓰면서 거부감이 많이 사라진 것 같다는 느낌을 받았습니다. 
특히 원래는 어떤 글을 써야할지 항상 고민을 하면서 힘들어했는데, 스터디를 하면서 여러 방식으로 글을 써보는 경험을 하면서 제가 어떤 글을 쓰고싶어 하는지에 대해 어느 정도 알게 되어 좋았습니다.

또 글을 쓰면서 생각보다 내가 안다고 착각했던 지식들이 많았다는 것도 알게 되었습니다. 그래서 좀 더 글을 쓸 때 꼼꼼하게 체크를 하게 되었고, 그러면서 자연스럽게 docs를 찾아보는 습관도 생기고 실제로 디버깅도 많이 했던 경험이 저에게 도움이 많이 되었던 것 같습니다.

마지막으로 이런 스터디 열어주셔서 감사하고 참여하신 모든 분들 수고 많으셨다는 말을 드리고 싶네요.
